//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.ServiceReferenceAffichagePrix {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAffichagePrix.IAffichagePrix")]
    public interface IAffichagePrix {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAffichagePrix/GetPrixCodePostal", ReplyAction="http://tempuri.org/IAffichagePrix/GetPrixCodePostalResponse")]
        FuelTracker_Lib.Station[] GetPrixCodePostal(int codePostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAffichagePrix/GetPrixCodePostal", ReplyAction="http://tempuri.org/IAffichagePrix/GetPrixCodePostalResponse")]
        System.Threading.Tasks.Task<FuelTracker_Lib.Station[]> GetPrixCodePostalAsync(int codePostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAffichagePrix/GetPrixDepartement", ReplyAction="http://tempuri.org/IAffichagePrix/GetPrixDepartementResponse")]
        string[] GetPrixDepartement(int departement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAffichagePrix/GetPrixDepartement", ReplyAction="http://tempuri.org/IAffichagePrix/GetPrixDepartementResponse")]
        System.Threading.Tasks.Task<string[]> GetPrixDepartementAsync(int departement);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAffichagePrixChannel : WcfService1.ServiceReferenceAffichagePrix.IAffichagePrix, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AffichagePrixClient : System.ServiceModel.ClientBase<WcfService1.ServiceReferenceAffichagePrix.IAffichagePrix>, WcfService1.ServiceReferenceAffichagePrix.IAffichagePrix {
        
        public AffichagePrixClient() {
        }
        
        public AffichagePrixClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AffichagePrixClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AffichagePrixClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AffichagePrixClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FuelTracker_Lib.Station[] GetPrixCodePostal(int codePostal) {
            return base.Channel.GetPrixCodePostal(codePostal);
        }
        
        public System.Threading.Tasks.Task<FuelTracker_Lib.Station[]> GetPrixCodePostalAsync(int codePostal) {
            return base.Channel.GetPrixCodePostalAsync(codePostal);
        }
        
        public string[] GetPrixDepartement(int departement) {
            return base.Channel.GetPrixDepartement(departement);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPrixDepartementAsync(int departement) {
            return base.Channel.GetPrixDepartementAsync(departement);
        }
    }
}
